In [72]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.metrics import confusion_matrix


In [73]:
iris = load_iris()


In [74]:
features=iris.data
target=iris.target


In [75]:
X_train, X_test, y_train, y_test = train_test_split(features,target, random_state = 50, test_size = 0.50)


In [83]:
#for decision tree
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
clfP = DecisionTreeClassifier(criterion='entropy',max_depth=4,max_leaf_nodes= 5,min_samples_split= 10,splitter='best',
                                random_state= 1)
clfP.fit(X_train,y_train)

print("\nFor Not Pruned model")
predict = clf.predict(X_test)
print("Train data accuracy:",accuracy_score(y_true = y_train, y_pred=clf.predict(X_train)))
print("Test data accuracy:",accuracy_score(y_true = y_test, y_pred=predict))
y_pred = clf.fit(X_train, y_train).predict(X_test)
print(confusion_matrix(y_test, y_pred))





print("\nFor Pruned model")
prunedpredict = clfP.predict(X_test)
print("Train data accuracy:",accuracy_score(y_true = y_train, y_pred=clfP.predict(X_train)))
print("Test data accuracy:",accuracy_score(y_true = y_test, y_pred=predict))
y_pred = clfP.fit(X_train, y_train).predict(X_test)
print(confusion_matrix(y_test, y_pred))


For Not Pruned model
Train data accuracy: 1.0
Test data accuracy: 0.9733333333333334
[[25  0  0]
 [ 0 25  1]
 [ 0  1 23]]

For Pruned model
Train data accuracy: 0.9733333333333334
Test data accuracy: 0.9733333333333334
[[25  0  0]
 [ 0 25  1]
 [ 0  1 23]]


In [85]:
#for decision tree
for i in range (3,7):
    print("\nfor K =",i)
    cltkn= KNeighborsClassifier(n_neighbors = i)
    cltkn.fit(X_train,y_train)
    
    
    predict = cltkn.predict(X_test)
    print("Train data accuracy:",accuracy_score(y_true = y_train, y_pred=cltkn.predict(X_train)))
    print("Test data accuracy:",accuracy_score(y_true = y_test, y_pred=predict))
    y_pred = cltkn.fit(X_train, y_train).predict(X_test)
    print(confusion_matrix(y_test, y_pred))
    


for K = 3
Train data accuracy: 0.96
Test data accuracy: 0.96
[[25  0  0]
 [ 0 23  3]
 [ 0  0 24]]

for K = 4
Train data accuracy: 0.96
Test data accuracy: 0.9733333333333334
[[25  0  0]
 [ 0 24  2]
 [ 0  0 24]]

for K = 5
Train data accuracy: 0.96
Test data accuracy: 0.96
[[25  0  0]
 [ 0 23  3]
 [ 0  0 24]]

for K = 6
Train data accuracy: 0.96
Test data accuracy: 0.9733333333333334
[[25  0  0]
 [ 0 24  2]
 [ 0  0 24]]
